#!/bin/bash
echo "go away, $USER " '!';\
read -r str; \
#echo "txt was $str";\
if [ "$str" == "it doesn't have to be a snowman" ];\
then echo "             \   |   /
              \_ | _/
             /_    _\
            /        \
           (  0    0  )
            \    V   /
          \\| \   u  /  \|/
           \  ------   /
            \/       \/
            |    O    |
             \_______/
             /       \
            |    O    |
             \_______/       ";
 fi
